[plugins]
cutterslade-analyze = { id = "ca.cutterslade.analyze", version = "1.9.2" }

[versions]
jackson-version = "2.16.1"
jupiter-version = "5.10.2"
ktor2-version = "2.3.8"
navfelles-token-version = "4.1.3"

[libraries]
jackson-datatypejsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-version" }
jackson-datatypejdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-version" }
jackson-modulekotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }

ktor2-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor2-version" }
ktor2-clientcore = { module = "io.ktor:ktor-client-core", version.ref = "ktor2-version" }
ktor2-clientloggingjvm = { module = "io.ktor:ktor-client-logging-jvm", version.ref = "ktor2-version" }
ktor2-clientauth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor2-version" }
ktor2-clientlogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor2-version" }
ktor2-clientciojvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor2-version" }
ktor2-clientcontentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor2-version" }
ktor2-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor2-version" }
ktor2-clientmock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor2-version" }
ktor2-servertests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor2-version" }

navfelles-tokenclientcore = { module = "no.nav.security:token-client-core", version.ref = "navfelles-token-version" }
navfelles-tokenvalidationktor2 = { module = "no.nav.security:token-validation-ktor-v2", version.ref = "navfelles-token-version" }

test-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter-version" }
test-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter-version" }
test-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter-version" }
test-kotest-assertionscore = { module = "io.kotest:kotest-assertions-core", version = "5.8.0" }
test-mockk = { module = "io.mockk:mockk", version = "1.13.9" }